server:
  port: 8081
#postgres
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  threads:
    virtual:
      enabled: true

jwt:
  secretkey:
  audience: finflexteamwois
  issuer: wois
api:
  url: ${RATES_URL}
logging:
  config: classpath:logback-spring.xml